package com.heston.adapter.con1.wizard;

import com.informatica.tools.adapters.ui.appsdk.wizard.NewDefaultAppDataObjectWizard;

public class Con1DataObjectWizard extends NewDefaultAppDataObjectWizard  {
    	/* 
    	 * Get adapter id  
    	 *************************************
    	 * AUTOGENERATED CODE : DO NOT CHANGE
    	 */
    	@Override
    	protected String getAdapterId() {
    		return "com.heston.adapter.con1";
    	}

}